# Generated by Django 2.0.3 on 2018-10-18 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModelClass',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.BaseClass')),
                ('first_name', models.CharField(help_text='Patients First name', max_length=100)),
            ],
            bases=('api.baseclass',),
        ),
    ]
