# Generated by Django 2.0.3 on 2018-10-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diag'),
    ]

    operations = [
        migrations.AddField(
            model_name='diag',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.PatientModelClass'),
            preserve_default=False,
        ),
    ]
