# Generated by Django 2.0.3 on 2018-10-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_diag_patient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diag',
            unique_together={('name', 'patient')},
        ),
    ]
